[package]
name = "nsncd"
version = "1.4.1"
authors = [
    "Ben Linsay <ben.linsay@twosigma.com>",
    "Geoffrey Thomas <geoffrey.thomas@twosigma.com>",
    "Leif Walsh <leif.walsh@twosigma.com>",
]
edition = "2021"
description = "The name service non-caching daemon"
readme = "README.md"
repository = "https://github.com/twosigma/nsncd"
license = "Apache-2.0"

[dependencies]
anyhow = "^1.0"
atoi = "^0.4"
slog = "^2.7"
slog-async = "^2.7"
slog-term = "^2.9"
crossbeam-channel = "^0.5"
nix = "^0.26"
num-derive = "^0.3"
num-traits = "^0.2"
sd-notify = "^0.4"
static_assertions = "1.1.0"
dns-lookup = "1.0.8"

[dev-dependencies]
criterion = "^0.3"
temp-env = "^0.3"

[[bench]]
name = "user"
harness = false
